services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green

  blue:
    image: litzi123/vobe:v1
    container_name: vobe_blue
    ports:
      - "8081:80"   # Blue ahora está en el puerto 8081

  green:
    image: litzi123/vobe:v2
    container_name: vobe_green
    ports:
      - "8082:80"   # Green ahora está en el puerto 8082
